---
- name: Install httpd
  yum:
    name: httpd
    state: present
- name: Start httpd
  service:
    name: httpd
    state: started
- name: Open httpd port on firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
