# openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout node_exporter.key -out node_exporter.crt -subj "/C=BE/ST=Antwerp/L=Brasschaat/O=Inuits/CN=localhost" 
tls_server_config:
  cert_file: prom.crt
  key_file: prom.key

# --web.config.file=web.yml  --config.file=prometheus.yml
basic_auth_users:
  admin: $2y$10$zCuKBSRktt1Q7KRliIaBlejdN6xu1lnLMa5oDg2sRDHEwZsyXjVU2
  tecnomen: $2y$10$zCuKBSRktt1Q7KRliIaBlejdN6xu1lnLMa5oDg2sRDHEwZsyXjVU2