apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
  - targetPort: 80 # backend expose
    port: 80 # service expose
  selector:
    app: myapp
    type: back-end
