---
- name: Deploy application
  hosts: application_servers
  tasks:
  - name: Copy application code
    copy:
      src: app_code/
      dest: /opt/application/
    notify: Restart application service
  handlers:
    - name: Restart application service
      service:
        name: application_service
        state: restarted