---
- name: Add or update user password
  hosts: all

  tasks:
  - name: Change user password
    user:
      name: alice
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"

# ansible-playbook -C change-user-password.yml --extra-vars newpassword=password      