---
- name: Setup prod-1 httpd
  hosts: prod-1
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Start httpd
    service:
      name: httpd
      state: started
  - name: Open httpd port on firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
      
- name: Setup prod-2 httpd  
  hosts: prod-2
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Start httpd
    service:
      name: httpd
      state: started

