---
- name: Setup httpd and open firewall port
  hosts: all
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Start httpd
    service:
      name: httpd
      state: started
  - name: Open port 80
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart firewalld
    service:
      name: firewalld
      state: reloaded