pipeline {
    agent any

    stages {
        stage('without docker') {
            steps {
                sh 'echo without docker'
            }
        }
        stage('with docker') {
            agent {
                docker {
                    image 'node:18-alpine'
                }
            }
            steps {
                sh 'echo with docker'
                sh 'npm --version'
            }
        }
    }
}
