apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: choonsiong/kube-network-user:latest
          env:
            # To use the environment variable AUTH_SERVICE_SERVICE_HOST, remember to start services first,
            # before deployment: https://www.udemy.com/course/docker-kubernetes-the-practical-guide/learn/lecture/22627933#questions/16537692
            - name: AUTH_ADDRESS
              value: 10.97.36.125
