name: Deployment
on:
  push:
    branches:
      - main
      - dev
env: # environment variables
  MONGODB_DB_NAME: demo-db # available in all jobs
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.15pwqcc.mongodb.nets
      MONGODB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }} # secret in github setting
      MONGODB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }} 
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "MONGODB_USERNAME - ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME - ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME - $MONGO_DB_NAME"