pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'ubuntu:noble'
                    args '-u root'
                }
            }
            
            steps {
                sh 'apt upgrade; apt update; apt install -y jq; jq --version'
            }
        }
    }
}