server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # 'loki' is the container name of the loki container

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      team: devops
      env: prod
      component:
      level:
  pipeline_stages:
  - logfmt:
      mapping:
        component:
        level:
  - labels:
      component:
      level: