name: Push Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: echo "testing..."      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: echo "building..."
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "deploying..."